const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand, ScanCommand } = require('@aws-sdk/lib-dynamodb');
require('dotenv').config({ path: './.env' });

const client = new DynamoDBClient({ region: process.env.AWS_REGION || 'us-east-1' });
const docClient = DynamoDBDocumentClient.from(client);

const initialItems = [
  // ─── MORNING BRIEF STORIES ──────────────────────────────────────
  {
    id: 'brief_1',
    type: 'morning_brief',
    storyNumber: 1,
    order: 1,
    title: "Women's Cricket Final",
    description: 'India face Sri Lanka in the gold medal match — biggest game of the Asian Games for Indian cricket.',
    sport: 'Cricket',
    icon: '🏏',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'brief_2',
    type: 'morning_brief',
    storyNumber: 2,
    order: 2,
    title: 'Shooting Medal Push',
    description: 'Indian shooters target the podium in 10m Air Rifle Mixed Team and Skeet Qualification today.',
    sport: 'Shooting',
    icon: '🎯',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'brief_3',
    type: 'morning_brief',
    storyNumber: 3,
    order: 3,
    title: 'Badminton Knockouts',
    description: "India's men's and women's teams enter the quarter-finals — both sides aiming for the semis.",
    sport: 'Badminton',
    icon: '🏸',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'brief_4',
    type: 'morning_brief',
    storyNumber: 4,
    order: 4,
    title: "Men's Hockey Opener",
    description: "India return to Pool A action looking to build on yesterday's win with a stronger second outing.",
    sport: 'Hockey',
    icon: '🏑',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'brief_5',
    type: 'morning_brief',
    storyNumber: 5,
    order: 5,
    title: 'Boxing Debut',
    description: "Sakshi Chaudhary begins her campaign in Women's 54kg — a medal hopeful in her first Asian Games.",
    sport: 'Boxing',
    icon: '🥊',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ─── TODAY'S AGENDA EVENTS ──────────────────────────────────────
  {
    id: 'agenda_1',
    type: 'todays_agenda',
    order: 1,
    time: '08:00 AM',
    sport: 'Badminton',
    subEvent: "Women's Team Q/F",
    detail: 'India vs. Japan',
    statusType: 'live',
    statusLabel: 'LIVE',
    icon: '🏸',
    nodeColor: 'emerald',
    venue: 'Binjiang Gymnasium · Court 1',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_2',
    type: 'todays_agenda',
    order: 2,
    time: '08:15 AM',
    sport: 'Shooting',
    subEvent: '10m Air Rifle Mixed Team',
    detail: 'Qualification',
    statusType: 'live',
    statusLabel: 'LIVE',
    icon: '🎯',
    nodeColor: 'emerald',
    venue: 'Fuyang Yinhu Sports Centre',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_3',
    type: 'todays_agenda',
    order: 3,
    time: '09:30 AM',
    sport: 'Table Tennis',
    subEvent: 'R16 Knockouts',
    detail: "Women's / Men's",
    statusType: 'up_next',
    statusLabel: 'UP NEXT',
    icon: '🏓',
    nodeColor: 'amber',
    venue: 'Gongshu Canal Sports Park',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_4',
    type: 'todays_agenda',
    order: 4,
    time: '09:30 AM',
    sport: "Men's Cricket T20",
    subEvent: 'World Cup / Friendly',
    detail: 'India vs. Japan',
    statusType: 'afternoon',
    statusLabel: 'AFTERNOON',
    icon: '🏏',
    nodeColor: 'blue',
    venue: 'Zhejiang Tech University Cricket Field',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_5',
    type: 'todays_agenda',
    order: 5,
    time: '10:00 AM',
    sport: "Women's Cricket T20 Final",
    subEvent: 'Gold Medal Match',
    detail: 'India vs Sri Lanka',
    statusType: 'afternoon',
    statusLabel: 'AFTERNOON',
    icon: '🏏',
    nodeColor: 'blue',
    venue: 'Pingfeng Campus Cricket Field',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_6',
    type: 'todays_agenda',
    order: 6,
    time: '12:00 PM',
    sport: 'Swimming',
    subEvent: "Men's 200m Freestyle",
    detail: 'Final',
    statusType: 'afternoon',
    statusLabel: 'AFTERNOON',
    icon: '🏊',
    nodeColor: 'blue',
    venue: 'Hangzhou Olympic Sports Center Natatorium',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_7',
    type: 'todays_agenda',
    order: 7,
    time: '02:00 PM',
    sport: 'Gymnastics',
    subEvent: "Women's Floor Final",
    detail: 'Medal Rounds',
    statusType: 'afternoon',
    statusLabel: 'AFTERNOON',
    icon: '🤸',
    nodeColor: 'blue',
    venue: 'Huanglong Sports Centre Gymnasium',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_8',
    type: 'todays_agenda',
    order: 8,
    time: '04:00 PM',
    sport: 'Archery',
    subEvent: "Men's Individual Final",
    detail: 'India vs Korea',
    statusType: 'afternoon',
    statusLabel: 'AFTERNOON',
    icon: '🏹',
    nodeColor: 'blue',
    venue: 'Fuyang Yinhu Sports Centre Archery Field',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agenda_9',
    type: 'todays_agenda',
    order: 9,
    time: '07:00 PM',
    sport: 'Boxing',
    subEvent: "Women's 54kg Semi-Final",
    detail: 'Sakshi Choudhary',
    statusType: 'afternoon',
    statusLabel: 'AFTERNOON',
    icon: '🥊',
    nodeColor: 'blue',
    venue: 'Hangzhou Gymnasium',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ─── RADAR CARDS ───────────────────────────────────────────────
  {
    id: 'radar_1',
    type: 'radar_card',
    order: 1,
    sport: 'Shooting',
    event: '10m Air Rifle',
    round: 'Mixed Team · Qual',
    status: 'LIVE',
    isLive: true,
    icon: '🎯',
    themeColor: 'emerald',
    venue: 'Fuyang Yinhu Sports Centre',
    teams: {
      teamA: 'India (Divyansh & Ramita)',
      teamB: 'China',
      scoreA: '632.8 (Rank 1)',
      scoreB: '631.5 (Rank 2)',
    },
    summary: 'India leading qualification stage with blistering precision shots.',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'radar_2',
    type: 'radar_card',
    order: 2,
    sport: 'Table Tennis',
    event: 'R16 Knockouts',
    round: "Women's / Men's",
    status: '09:30 AM',
    isLive: false,
    icon: '🏓',
    themeColor: 'purple',
    venue: 'Gongshu Canal Sports Park',
    teams: {
      teamA: 'Manika Batra (IND)',
      teamB: 'Miu Hirano (JPN)',
    },
    summary: 'High stakes Round of 16 clash for a spot in the quarter-finals.',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'radar_3',
    type: 'radar_card',
    order: 3,
    sport: "Men's T20",
    event: 'India vs Japan',
    round: 'Quarter Finals',
    status: '09:30 AM',
    isLive: false,
    icon: '🏏',
    themeColor: 'purple',
    venue: 'Zhejiang Tech University Cricket Field',
    teams: {
      teamA: 'India',
      teamB: 'Japan',
    },
    summary: 'Knockout cricket clash as Team India fields an explosive batting lineup.',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'radar_4',
    type: 'radar_card',
    order: 4,
    sport: 'Badminton',
    event: "Women's Singles",
    round: 'India vs Korea',
    status: '11:00 AM',
    isLive: false,
    icon: '🏸',
    themeColor: 'amber',
    venue: 'Binjiang Gymnasium',
    teams: {
      teamA: 'PV Sindhu (IND)',
      teamB: 'An Se-young (KOR)',
    },
    summary: 'Blockbuster gold medal showdown between world champions.',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'radar_5',
    type: 'radar_card',
    order: 5,
    sport: 'Athletics',
    event: 'Javelin Throw Final',
    round: "Neeraj Chopra · Men's",
    status: '02:30 PM',
    isLive: false,
    icon: '🏃',
    themeColor: 'cyan',
    venue: 'Hangzhou Olympic Sports Expo Center',
    teams: {
      teamA: 'Neeraj Chopra (IND)',
      teamB: 'Arshad Nadeem (PAK)',
    },
    summary: 'Reigning Olympic champion Neeraj Chopra defends his Asian Games gold.',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'radar_6',
    type: 'radar_card',
    order: 6,
    sport: 'Boxing',
    event: '54kg Semi-Finals',
    round: 'Preeti Pawar · Bout',
    status: '05:00 PM',
    isLive: false,
    icon: '🥊',
    themeColor: 'rose',
    venue: 'Hangzhou Gymnasium',
    teams: {
      teamA: 'Preeti Pawar (IND)',
      teamB: 'Yuan Chang (CHN)',
    },
    summary: 'Crucial semi-final bout securing an Olympic quota spot.',
    active: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'config_welcome',
    type: 'welcome_config',
    actionSubtitle: 'Top action today · Asian Games',
    agendaDateTitle: 'Tuesday · 23 September',
    briefSubtitle: 'Top 5 stories to know today',
    updatedAt: Date.now(),
  }
];

async function seed() {
  console.log('Seeding initial data into homeDatabase...');
  for (const item of initialItems) {
    await docClient.send(new PutCommand({
      TableName: 'homeDatabase',
      Item: item,
    }));
    console.log('Seeded:', item.id, `(${item.type})`);
  }
  const scan = await docClient.send(new ScanCommand({ TableName: 'homeDatabase' }));
  console.log('Success! Total items now in homeDatabase:', scan.Items.length);
}

seed().catch(console.error);
